<?php

namespace Database\Seeders;

use App\Models\Member;
use App\Models\MemberClass;
use Illuminate\Database\Seeder;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $classMap = MemberClass::pluck('id', 'code')->all();

        $members = [
            ['persi_code' => 'PJTG.01', 'name' => 'RSUP dr. Kariadi', 'class_code' => '1', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.02', 'name' => 'RSIA Anugerah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.03', 'name' => 'RSIA Bunda', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.04', 'name' => 'RSUD dr. Adhyatma, MPH', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.05', 'name' => 'RSIA Gunung Sawo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.06', 'name' => 'RS Panti Wilasa Citarum', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.07', 'name' => 'RS Panti Wilasa Dr.Cipto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.08', 'name' => 'RS Banyumanik', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.09', 'name' => 'RS Roemani Muh. Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.10', 'name' => 'RST Bhakti Wira Tamtama', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.11', 'name' => 'RSI Sultan Agung Semarang', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.12', 'name' => 'RS ST Elisabeth Semarang', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.13', 'name' => 'RSJD dr. Amino Gondohutomo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.14', 'name' => 'RS Telogorejo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.15', 'name' => 'RSU William Booth', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.16', 'name' => 'RSIA Kusuma Pradja', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.17', 'name' => 'RS Hermina Pandanaran', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.18', 'name' => 'RSIA Plamongan Indah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.19', 'name' => 'RSD KRMT Wongsonegoro', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.20', 'name' => 'RS Permata Medika Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.21', 'name' => 'RS Bhayangkara AKPOL', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.22', 'name' => 'RS Bhayangkara Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.23', 'name' => 'RS Khusus Bedah Columbia Asia Semarang', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.24', 'name' => 'RS Hermina Banyumanik', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.25', 'name' => 'RS Nasional Diponegoro', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.26', 'name' => 'RSIA Siloam Hospitals Semarang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.27', 'name' => 'RSIGM Sultan Agung Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.28', 'name' => 'RSU Banyumanik 2', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.29', 'name' => 'RS Primaya Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.30', 'name' => 'RS Mata JEC Candi @ Semarang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.31', 'name' => 'RS Keluarga Sehat III Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.32', 'name' => 'RS Cepoko', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.33', 'name' => 'RS Samsoe Hidajat', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.34', 'name' => 'RSGM Universitas  Muhammadiyah Semarang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.35', 'name' => 'RSIA Ananda Pasar Ace', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.36', 'name' => 'RS UNIMUS', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.37', 'name' => 'RS Pelita Anugerah', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.38', 'name' => 'RSI NU Demak', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.39', 'name' => 'RSUD Sunan Kalijaga Demak', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.40', 'name' => 'RSUD Sultan Fatah Demak', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.41', 'name' => 'RS Hj. Fatimah Sulhan PKU Muh. Demak', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.42', 'name' => 'RS Charlie Hospital Demak', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.43', 'name' => 'RSUD dr. Gondo Suwarno', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.44', 'name' => 'RSUD dr. Gunawan Mangun Kusumo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.45', 'name' => 'RS Bina Kasih', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.46', 'name' => 'RS Ken Saras', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.47', 'name' => 'RSU Kusuma Ungaran', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.48', 'name' => 'RS At-Tin Hospital', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.49', 'name' => 'RS Paru dr. Ario Wirawan', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.50', 'name' => 'RSUD Salatiga', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.51', 'name' => 'RSU Puri Asih', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.52', 'name' => 'RST dr. Asmir', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.53', 'name' => 'RSIA Hermina Mutiara Bunda', 'class_code' => '1', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.54', 'name' => 'RSI Tunas Harapan Salatiga', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.55', 'name' => 'RSUD dr. H. Soewondo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.56', 'name' => 'RS Muhammadiyah Darul Istiqomah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.57', 'name' => 'RS Islam Kendal', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.58', 'name' => 'RS Baitul Hikmah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.59', 'name' => 'RS PKU \'Aisyiyah Kendal', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.60', 'name' => 'RS Charlie Hospital', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.61', 'name' => 'RS PKU Muh. Boja', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.62', 'name' => 'RSUD dr. R. Soedjati Soemodiardjo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.63', 'name' => 'RS Panti Rahayu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.64', 'name' => 'RS PKU Muh Gubug', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.65', 'name' => 'RS Permata Bunda', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.66', 'name' => 'RSU Habibullah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.67', 'name' => 'RSI Purwodadi', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.68', 'name' => 'RS Ortopedi Siaga Utama', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.69', 'name' => 'RS Sekar Laras', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.70', 'name' => 'RS Marganingsih', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.71', 'name' => 'RSU Trimedika Ketapang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.72', 'name' => 'RSUD Ki Ageng Selo Wirosari', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.73', 'name' => 'RSUD Ki Ageng Getas Pendowo Gubug', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.74', 'name' => 'RS Permata Utama', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.75', 'name' => 'RSI Sunan Kudus', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.76', 'name' => 'RSUD dr. Loekmono Hadi Kudus', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.77', 'name' => 'RSIA Permata Hati Kudus', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.78', 'name' => 'RS Mardi Rahayu', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.79', 'name' => 'RSU Nurussyifa Kudus', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.80', 'name' => 'RS \'Aisyiyah Kudus', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.81', 'name' => 'RSIA Harapan Bunda', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.82', 'name' => 'RSU Kumala Siwi Mijen', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.83', 'name' => 'RS Sarkies \'Aisyiyah Kudus', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.84', 'name' => 'RSIA Miriam Kudus', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.85', 'name' => 'RSUD RA Kartini', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.86', 'name' => 'RSI Sultan Hadlirin', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.87', 'name' => 'RS Graha Husada', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.88', 'name' => 'RSUD dr. Rehatta', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.89', 'name' => 'RS PKU Muh Mayong Jepara', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.90', 'name' => 'RS PKU Aisyiyah Jepara', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.91', 'name' => 'RSUD RAA Soewondo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.92', 'name' => 'RS Mitra Bangsa Pati', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.93', 'name' => 'RS Keluarga Sehat', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.94', 'name' => 'RSI Pati', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.95', 'name' => 'RSU Fastabiq Sehat PKU Muh Pati', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.96', 'name' => 'RSU Sebening Kasih', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.97', 'name' => 'RSU Budi Agung', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.98', 'name' => 'RS Keluarga Sehat Tayu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.99', 'name' => 'RSU As-Suyuthiyyah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.100', 'name' => 'RSUD Kayen Pati', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.101', 'name' => 'RSUD dr. R. Soetrasno', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.102', 'name' => 'RS Islam Arafah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.103', 'name' => 'RS Bhina Bhakti Husada', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.104', 'name' => 'RS PKU Muhammadiyah Pamotan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.105', 'name' => 'RSUD dr. R. Soeprapto Cepu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.106', 'name' => 'RS PKU Muhammadiyah Cepu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.107', 'name' => 'RSUD dr. R. Soetijono Blora', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.108', 'name' => 'RSU Permata Blora', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.109', 'name' => 'RS PKU Muhammadiyah Blora', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.110', 'name' => 'RSIA Annisa Blora', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.111', 'name' => 'RSUD Samin Surosentiko Randublatung', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.112', 'name' => 'RSUD Batang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.113', 'name' => 'RS Qolbu Insan Mulia (QIM)', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.114', 'name' => 'RSUD Limpung', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.115', 'name' => 'RSUD Kraton Pekalongan', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.116', 'name' => 'RSI PKU Muh. Pekajangan', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.117', 'name' => 'RSUD Kajen Pekalongan', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.118', 'name' => 'RSIA Aisyiyah Pekajangan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.119', 'name' => 'RS Prima Sehat Pekalongan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.120', 'name' => 'RS Ki Ageng Sedayu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.121', 'name' => 'RSU Budi Rahayu Pekalongan', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.122', 'name' => 'RS Siti Khodijah', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.123', 'name' => 'RS Karomah Holistic', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.124', 'name' => 'RSU Anugerah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.125', 'name' => 'RSU Aro', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.126', 'name' => 'RSUD Bendan Kota Pekalongan', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.127', 'name' => 'RS. H.A. Zaki Djunaid Pekalongan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.128', 'name' => 'RS Hermina Pekalongan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.129', 'name' => 'RSU Santa Maria Pemalang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.130', 'name' => 'RSUD dr. M. Ashari', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.131', 'name' => 'RS Muh. Rodliyah Achid Moga', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.132', 'name' => 'RSU Siaga Medika Pemalang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.133', 'name' => 'RS Prima Medika', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.134', 'name' => 'RSI Al Ikhlas', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.135', 'name' => 'RS Muhammadiyah Mardhatillah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.136', 'name' => 'RS Harapan Sehat Pemalang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.137', 'name' => 'RSU Comal Baru', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.138', 'name' => 'RSUD Kardinah', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.139', 'name' => 'RSU Islam Harapan Anda', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.140', 'name' => 'RSIA Kasih Ibu Tegal', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.141', 'name' => 'RS Mitra Keluarga Tegal', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.142', 'name' => 'RS Mitra Siaga Tegal', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.143', 'name' => 'RS PKU Muhammadiyah Tegal', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.144', 'name' => 'RSUD dr. Soeselo Slawi', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.145', 'name' => 'RSIA Pala Raya Tegal', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.146', 'name' => 'RSU Adella', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.147', 'name' => 'RSUD Suradadi', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.148', 'name' => 'RS Hawari Essa', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.149', 'name' => 'RS Harapan Sehat Slawi', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.150', 'name' => 'RS Mitra Keluarga Slawi', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.151', 'name' => 'RS Tk IV 04.07.01 Tegal', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.152', 'name' => 'RS Mitra Siaga Tarub', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.153', 'name' => 'RSUD Brebes', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.154', 'name' => 'RS Bhakti Asih Brebes', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.155', 'name' => 'RS Dedy Jaya', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.156', 'name' => 'RSU Islami Mutiara Bunda', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.157', 'name' => 'RSU Siti Asiyah Bumiayu', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.158', 'name' => 'RS Muh. Siti Aminah Bumiayu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.159', 'name' => 'RS Dera As-Syifa', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.160', 'name' => 'RS Amanah Mahmudah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.161', 'name' => 'RS Allam Medica', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.162', 'name' => 'RSIA Permata Insani', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.163', 'name' => 'RS Bhakti Asih Jatibarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.164', 'name' => 'RS Harapan Sehat Jatibarang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.165', 'name' => 'RS Harapan Sehat Bumiayu', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.166', 'name' => 'RSUD Bumiayu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.167', 'name' => 'RSUD Ir. Soekarno Kabupaten Brebes', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.168', 'name' => 'RSIA Nuzula', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.169', 'name' => 'RSI Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.170', 'name' => 'RSUD Prof. dr. Margono Soekarjo', 'class_code' => '1', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.171', 'name' => 'RS TK III 04.06.01 Wijayakusuma', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.172', 'name' => 'RS ST Elisabeth Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.173', 'name' => 'RSU Hidayah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.174', 'name' => 'RSU Sinar Kasih', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.175', 'name' => 'RSIA Budhi Asih', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.176', 'name' => 'RSIA Bunda Arif', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.177', 'name' => 'RS Orthopaedi Purwokerto', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.178', 'name' => 'RSKB "Jatiwinangun"', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.179', 'name' => 'RS Ananda Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.180', 'name' => 'RSU Bunda Purwokerto', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.181', 'name' => 'RS Gigi & Mulut UNSOED Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.182', 'name' => 'RS Dadi Keluarga Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.183', 'name' => 'RS Hermina Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.184', 'name' => 'RSUD Banyumas', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.185', 'name' => 'RSKB Mitra Ariva', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.186', 'name' => 'RSU An Ni\'mah Wangon', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.187', 'name' => 'RSU Wiradadi Husada', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.188', 'name' => 'RS PKU Muh Sumpiuh', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.189', 'name' => 'RS Siaga Medika Banyumas', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.190', 'name' => 'RSU Medika Lestari', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.191', 'name' => 'RS "JIH" Purwokerto', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.192', 'name' => 'RSUD Ajibarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.193', 'name' => 'RS Khusus Mata Purwokerto', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.194', 'name' => 'RSUD Cilacap', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.195', 'name' => 'RS Pertamina', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.196', 'name' => 'RSU Aprillia Cilacap', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.197', 'name' => 'RS Islam Fatimah', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.198', 'name' => 'RSU Santa Maria Cilacap', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.199', 'name' => 'RSUD Majenang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.200', 'name' => 'RSU Duta Mulya Majenang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.201', 'name' => 'RSU Afdila Cilacap', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.202', 'name' => 'RSIA Annisa Cilacap', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.203', 'name' => 'RSU Aghisna Medika Kroya', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.204', 'name' => 'RSU Priscilla Medical Center', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.205', 'name' => 'RSU Raffa Majenang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.206', 'name' => 'RSU Aghisna Medika Sidareja', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.207', 'name' => 'RSUD Hj. Anna Lasmanah', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.208', 'name' => 'RS Emanuel', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.209', 'name' => 'RSI Banjarnegara', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.210', 'name' => 'RSU PKU Muhammadiyah Banjarnegara', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.211', 'name' => 'RSUD dr. R. Goeteng Taroenadibrata', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.212', 'name' => 'RSIA Ummu Hani', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.213', 'name' => 'RSU Harapan Ibu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.214', 'name' => 'RSU Nirmala Purbalingga', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.215', 'name' => 'RSUD Panti Nugroho', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.216', 'name' => 'RS Islam At-Tin Husada Purbalingga', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.217', 'name' => 'RSU Siaga Medika Purbalingga', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.218', 'name' => 'RS PKU Muhammadiyah Purbalingga', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.219', 'name' => 'RSIA MPH Purbalingga', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.220', 'name' => 'RSUD dr. Soedirman', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.221', 'name' => 'RS PKU Muh Sruweng', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.222', 'name' => 'RSU Purwogondo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.223', 'name' => 'RSU Wijaya Kusuma Kebumen', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.224', 'name' => 'RS Palang Biru Gombong', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.225', 'name' => 'RSU PKU Muh Gombong', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.226', 'name' => 'RSU Purbowangi Gombong', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.227', 'name' => 'RS Permata Medika Kebumen', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.228', 'name' => 'RSUD Prembun Kebumen', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.229', 'name' => 'RS PKU Muhammadiyah Kutowinangun', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.230', 'name' => 'RS PKU Muhammadiyah Petanahan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.231', 'name' => 'RSUD KRT Setjonegoro Wonosobo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.232', 'name' => 'RSI Wonosobo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.233', 'name' => 'RSIA Adina', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.234', 'name' => 'RSU PKU Muhammadiyah Wonosobo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.235', 'name' => 'RS AISs Wonosobo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.236', 'name' => 'RSU Gunung Sawo Temanggung', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.237', 'name' => 'RS Kristen Ngesti Waluyo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.238', 'name' => 'RSU PKU Muh Temanggung', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.239', 'name' => 'RSUD dr. Djojonegoro', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.240', 'name' => 'RSUD Muntilan', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.241', 'name' => 'RSU Aisyiyah Muntilan', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.242', 'name' => 'RS N-21 Gemilang Magelang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.243', 'name' => 'RSU Syubbanul Wathon', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.244', 'name' => 'RSD Merah Putih', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.245', 'name' => 'RSJ Prof. dr. Soerojo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.246', 'name' => 'RSUD Tidar', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.247', 'name' => 'RST dr. Soedjono', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.248', 'name' => 'RSIA Gladiool', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.249', 'name' => 'RS Lestari Raharja', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.250', 'name' => 'RS Harapan Magelang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.251', 'name' => 'RSI Magelang', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.252', 'name' => 'RSUD Budi Rahayu', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.253', 'name' => 'RSIA Permata', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.254', 'name' => 'RSUD Tjitrowardojo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.255', 'name' => 'RS Palang Biru Kutoarjo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.256', 'name' => 'RS Panti Waluyo Purworejo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.257', 'name' => 'RSU Aisyiyah Purworejo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.258', 'name' => 'RSU Purwa Husada', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.259', 'name' => 'RSU Ananda Purworejo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.260', 'name' => 'RSU Budi Sehat', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.261', 'name' => 'RSU Kasih Ibu Purworejo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.262', 'name' => 'RS Amanah Umat', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.263', 'name' => 'RSU Islam Purworejo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.264', 'name' => 'RSUD dr. Moewardi', 'class_code' => '1', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.265', 'name' => 'RS Brayat Minulya', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.266', 'name' => 'RS dr. Oen Surakarta', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.267', 'name' => 'RSI Kustati', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.268', 'name' => 'RS Panti Waluyo Surakarta', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.269', 'name' => 'RS TK. IV Slamet Riyadi Surakarta', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.270', 'name' => 'RS Kasih Ibu Surakarta', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.271', 'name' => 'RS PKU Muh Surakarta', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.272', 'name' => 'RS Triharsi', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.273', 'name' => 'RSJD dr. Arif Zainudin Surakarta', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.274', 'name' => 'RS Hermina Solo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.275', 'name' => 'RS Onkologi Solo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.276', 'name' => 'RSUP Surakarta', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.277', 'name' => 'RS JIH Solo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.278', 'name' => 'RS PKU Muhammadiyah Sampangan Surakarta', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.279', 'name' => 'RS Mata Solo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.280', 'name' => 'RSUD Bung Karno', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.281', 'name' => 'RSUD Ibu Fatmawati Soekarno', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.282', 'name' => 'RSUD Karanganyar', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.283', 'name' => 'RS PKU Muh Karanganyar', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.284', 'name' => 'RSU Jati Husada Karanganyar', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.285', 'name' => 'RSU Jafar Medika Karanganyar', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.286', 'name' => 'RS Indo Sehat', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.287', 'name' => 'RSIA Dian Pertiwi', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.288', 'name' => 'RSOP Prof. dr. R. Soeharso', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.289', 'name' => 'RSUD Ir. Soekarno Sukoharjo', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.290', 'name' => 'RS dr. Oen Solo Baru', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.291', 'name' => 'RS Nirmala Suri', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.292', 'name' => 'RSKB Karima Utama', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.293', 'name' => 'RS Indriati Solo Baru', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.294', 'name' => 'RS PKU Muhammadiyah Sukoharjo', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.295', 'name' => 'RS Islam Yarsis Surakarta', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.296', 'name' => 'RS Universitas Sebelas Maret', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.297', 'name' => 'RSUD Pandan Arang', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.298', 'name' => 'RSU Natalia', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.299', 'name' => 'RS Karanggede Sisma Medika', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.300', 'name' => 'RS Umi Barokah', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.301', 'name' => 'RSUD Waras Wiris', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.302', 'name' => 'RSUD Simo Boyolali', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.303', 'name' => 'RS Asy Syifa\' Sambi Boyolali', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.304', 'name' => 'RS PKU \'Aisyiyah Boyolali', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.305', 'name' => 'RS Hidayah Boyolali', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.306', 'name' => 'RS Indriati Boyolali', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.307', 'name' => 'RSU Islam Banyu Bening Boyolali', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.308', 'name' => 'RSU Islam Boyolali', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.309', 'name' => 'RSUP dr. Soeradji Tirtonegoro', 'class_code' => '1', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.310', 'name' => 'RSJD dr. RM Soedjarwadi Klaten', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.311', 'name' => 'RS Cakra Husada', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.312', 'name' => 'RSU Islam Klaten', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.313', 'name' => 'RSU Aisyiah Klaten', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.314', 'name' => 'RSU Diponegoro Dua Satu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.315', 'name' => 'RS PKU Muh. Delanggu', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.316', 'name' => 'RS PKU Muhammadiyah Jatinom', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.317', 'name' => 'RSUD Bagas Waras', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.318', 'name' => 'RS Mitra Keluarga Husada', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.319', 'name' => 'RSU Islam Cawas-Klaten', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.320', 'name' => 'RS PKU Muhammadiyah Pedan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.321', 'name' => 'RS PKU Muhammadiyah Prambanan', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.322', 'name' => 'RSU Mardi Lestari', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.323', 'name' => 'RSUD dr. Soehadi Prijonegoro Sragen', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.324', 'name' => 'RSI Amal Sehat Sragen', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.325', 'name' => 'RSU Assalam Gemolong', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.326', 'name' => 'RSIA Restu Ibu Sragen', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.327', 'name' => 'RSU Sarila Husada Sragen', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.328', 'name' => 'RSU Rizky Amalia', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.329', 'name' => 'RSUD dr. Soeratno Gemolong', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.330', 'name' => 'RSU PKU Muhammadiyah Sragen', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.331', 'name' => 'RSU Islam YAKSSI Gemolong', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.332', 'name' => 'RSU Saras Ibnu Sina Sukowati', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.333', 'name' => 'RSUD Sukowati Tangen Sragen', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.334', 'name' => 'RSU Hastuti Sragen', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.335', 'name' => 'RSUD dr. Soediran Mangun Sumarso', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.336', 'name' => 'RS Muhammadiyah Selogiri Wonogiri', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.337', 'name' => 'RS Hermina Wonogiri', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.338', 'name' => 'RS Amal Sehat Wonogiri', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.339', 'name' => 'RS Fitri Candra', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.340', 'name' => 'RS Astrini Wonogiri', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.341', 'name' => 'RSU Maguan Husada', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.342', 'name' => 'RS Mulia Hati Wonogiri', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.343', 'name' => 'RS Mardi Rahayu Kudus', 'class_code' => '2', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.344', 'name' => 'RS Panti Wilasa Citarum Semarang', 'class_code' => '3', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.345', 'name' => 'RS Indo Sehat Karanganyar', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
            ['persi_code' => 'PJTG.346', 'name' => 'RSIA Permata Purworejo', 'class_code' => '4', 'address' => null, 'email' => null, 'pic_whatsapp' => null],
        ];

        foreach ($members as $m) {
            $classId = $m['class_code'] !== '' && isset($classMap[$m['class_code']])
                ? $classMap[$m['class_code']]
                : null;

            $dues = 0;
            if ($classId) {
                $class = MemberClass::find($classId);
                $dues = $class ? (int) $class->default_dues_amount : 0;
            }

            Member::updateOrCreate(
                ['persi_code' => $m['persi_code']],
                [
                    'name' => $m['name'],
                    'member_class_id' => $classId,
                    'dues_amount' => $dues,
                    'address' => $m['address'],
                    'email' => $m['email'],
                    'pic_whatsapp' => $m['pic_whatsapp'],
                    'is_active' => true,
                ]
            );
        }
    }
}